#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Apr 09 21:49:55 BST 2023
# SW Build 3788238 on Tue Feb 21 19:59:23 MST 2023
#
# IP Build 3783773 on Tue Feb 21 23:41:56 MST 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim TDNN_TB_func_impl -key {Post-Implementation:sim_1:Functional:TDNN_TB} -tclbatch TDNN_TB.tcl -view /home/matthew/shared/NeuralNetwork/TDNN_TB_behav.wcfg -log simulate.log"
xsim TDNN_TB_func_impl -key {Post-Implementation:sim_1:Functional:TDNN_TB} -tclbatch TDNN_TB.tcl -view /home/matthew/shared/NeuralNetwork/TDNN_TB_behav.wcfg -log simulate.log

